from __future__ import annotations

from enum import Enum


class Stage(str, Enum):
    # High-level run lifecycle
    RUN = "RUN"

    # Input
    LOAD_OPERATOR_CONFIG = "LOAD_OPERATOR_CONFIG"
    LOAD_VARIABLE_MAPPING = "LOAD_VARIABLE_MAPPING"
    LOAD_WORKBOOK = "LOAD_WORKBOOK"
    GROUP_ROWS = "GROUP_ROWS"

    # Per-section processing (keyed by A,C,F,H)
    SECTION_VALIDATE = "SECTION_VALIDATE"
    SECTION_SHEET_NAME = "SECTION_SHEET_NAME"
    SECTION_PARSE = "SECTION_PARSE"
    SECTION_MAX_RULES = "SECTION_MAX_RULES"

    # Output
    EXPORT_ACTIVITY_INIT = "EXPORT_ACTIVITY_INIT"
    EXPORT_SECTION_SHEET = "EXPORT_SECTION_SHEET"
    EXPORT_SECTION_CONFLUENCE = "EXPORT_SECTION_CONFLUENCE"
    EXPORT_ACTIVITY_PLACEHOLDER = "EXPORT_ACTIVITY_PLACEHOLDER"
    EXPORT_ACTIVITY_SAVE_WORKBOOK = "EXPORT_ACTIVITY_SAVE_WORKBOOK"
    EXPORT_ACTIVITY_DOCS = "EXPORT_ACTIVITY_DOCS"
